# Generated by Django 6.1.1 on 2026-09-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='test_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Ссылка на тест для оценки знаний'),
        ),
    ]
