# Generated by Django 6.1.1 on 2026-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_lecture_test_url'),
        ('users', '0002_department_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='users.department', verbose_name='Доступна отделам'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Доступна всем пользователям'),
        ),
    ]
