# Generated by Django 6.1.1 on 2026-10-01 15:30

import django.db.models.deletion
import player.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_lecture_departments_lecture_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='has_practice',
            field=models.BooleanField(default=False, verbose_name='Практическая часть'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='practice_task',
            field=models.TextField(blank=True, verbose_name='Задание для практики'),
        ),
        migrations.CreateModel(
            name='PracticeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Сдано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='player.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to=player.models.practice_upload_path, verbose_name='Файл работы')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='player.practicesubmission')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='practicesubmission',
            constraint=models.UniqueConstraint(fields=('lecture', 'user'), name='unique_lecture_submission'),
        ),
    ]
